language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
  - "pypy3"
services:
  - cassandra
install:
  - pip install coveralls
  - python setup.py -q install
script:
  - pip install -U cassandra-driver
  - coverage run --source=ripozo_cassandra setup.py test
after_success:
  coveralls