language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
services:
  - cassandra
before_install:
  - pip install coveralls
script:
  - pip install -U --pre cassandra-driver
  - pip install -U ripozo
  - python setup.py -q install
  - coverage run --source=ripozo_cassandra setup.py test
after_success:
  coveralls
